"""added email to user

Revision ID: 543586041bb9
Revises: c945cd888f9c
Create Date: 2022-10-17 17:49:25.253680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543586041bb9'
down_revision = 'c945cd888f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
